---
title: "PCA for Training Data"
author: "Tanner Reece"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(mice)
library(parallel)
library(dplyr)
library(psych)
library(factoextra)
library(tidyverse)
library(GGally)

knitr::opts_knit$set(root.dir = "/Users/Tanner/Library/CloudStorage/Box-Box/I2DB Datathon 2024")


```

# Importing Data and Labels
```{r}
#labels 
labels <- read_rds("./data/raw/Training_Set.RDS") %>% 
  dplyr::select(X1Yr_Death)
# Loads in imputed data sets
imputed_train <- read_rds("./data/processed/train_set_imputed.RDS")

#Selects continuous variables
train_pca_data <- imputed_train %>% dplyr::select_if(is.numeric)

```

# Initial PC assessments and performing PCA
```{r}
#Determines how many meaningful PCs there are. I.e. how many PCs capture more variance than that due to
#random chance
fa.parallel(train_pca_data, fa = "pc")

#Overall MSA is 0.84, which suggests data are highly suitable for PCA
KMO(train_pca_data)


#Extracting 12 components, no rotation
train_pca <- prcomp(train_pca_data, 
                    rank = 12, center = TRUE, scale. = TRUE, retx = FALSE)
```

#PCA Descriptives and PCA Visualizations
```{r}
#12 components provides 74.1% of Variance
summary(train_pca)
fviz_screeplot(train_pca, ncp = 12, addlabels = TRUE)

#Plotting relationships between PCs and coloring by training label
predict(train_pca, train_pca_data) %>% as.data.frame() %>% mutate(labels = labels$X1Yr_Death) %>% 
  ggpairs(aes(color = labels))

#Determining which variables load highest on each PC
loadings <- train_pca$rotation %>% as.data.frame() %>% rownames_to_column(var="varname") 

map(names(loadings[,-1]), function(x) {
  high_loadings <- loadings %>% 
    dplyr::select(varname, x) %>% 
    filter(abs(loadings[[x]]) > 0.3)
  return(high_loadings)
  })


```